baseURL = "https://linktree.puipuiminis.com/"
languageCode = "es-mx"
defaultContentLanguage = "en"

title = "Pui Pui Minis"
copyright = "&copy; 2026 Pui Pui Minis ðŸ¦”"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
   name = "Pui Pui Minis"
   headline = "Nos especializamos en pintar miniaturas y creamos mundos infinitos."
   image = "logo.jpg"  # path relative to static directory

  links = [

    { instagram = "https://instagram.com/puipuiminis32" },
    { facebook = "https://www.facebook.com/puipuiminis" },
    { tiktok = "https://tiktok.com/@puipuiminis" },
    { whatsapp = "https://wa.me/5563303533" },
    { email = "mailto:puipuiminis@gmail.com" },
    { copa-puipui = { href = "https://copapuipui.wordpress.com/una-tirada-de-gacha-abril-2024/", text = "Copa Pui Pui"} },
    { link = "https://www.puipuiminis.com/" },

    { pinterest = "https://pinterest.com/puipuiminis/_created" },
    # { mastodon = "https://mastodon.instance/@username" },
    # { bluesky = "https://bsky.app/profile/username" },
    # { twitter = "https://twitter.com/username" },
    # { x = "https://x.com/username" },
    # { youtube = "https://youtube.com/username" },


    # { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
    # { apple = "https://www.apple.com" },
    # { bandcamp = "https://username.bandcamp.com" },

    # { codepen = "https://codepen.io/username" },
    # { dev = "https://dev.to/username" },
    # { discord = "https://discord.gg/invitecode" },
    # { dribbble = "https://dribbble.com/username" },
    # { flickr = "https://www.flickr.com/photos/username/" },
    # { foursquare = "https://foursquare.com/username" },
    # { github = "https://github.com/username" },
    # { gitlab = "https://gitlab.com/username" },
    # { google = "https://www.google.com/" },
    # { keybase = "https://keybase.io/username" },
    # { kickstarter = "https://www.kickstarter.com/profile/username" },
    # { lastfm = "https://last.fm/user/username" },
    # { linkedin = "https://linkedin.com/in/username" },
    # { medium = "https://medium.com/username" },
    # { microsoft = "https://www.microsoft.com/" },
    # { patreon = "https://www.patreon.com/username" },
    # { reddit = "https://reddit.com/user/username" },
    # { slack = "https://workspace.url/team/userid" },
    # { snapchat = "https://snapchat.com/add/username" },
    # { soundcloud = "https://soundcloud.com/username" },
    # { spotify = "https://spotify.com/user/username" },
    # { stack-exchange = "https://stackexchange.com/users/userid/username" },
    # { stack-overflow = "https://stackoverflow.com/users/userid/username" },
    # { steam = "https://steamcommunity.com/profiles/userid" },
    # { telegram = "https://t.me/username" },
    # { threads = "https://threads.com/username" },
    # { tumblr = "https://username.tumblr.com" },
    # { twitch = "https://twitch.tv/username" },
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
